version: "3.8"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: whyakari/rinha:2.0
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "3001:3000"

  nginx:
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  db:
    image: mariadb:latest
    restart: always
    container_name: db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=love 
      - MYSQL_DATABASE=rinha 
      - MYSQL_PASSWORD=love
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "230MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

