version: "3.6"

services:
    api01: &api
        hostname: api01
        image: whyakari/rinha:2.0
        environment:
            - DATABASE_URL=mysql://root:love@tcp(db:3306)/rinha
            - DB_HOSTNAME=db
            - PORT=3000
            - POOL_MAX=5
            - POOL_MIN=5
        ports:
            - "3001:3000"
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: "0.55"
                    memory: "200MB"

    api02:
        <<: *api
        hostname: api02
        environment:
            - DB_HOSTNAME=db
            - PORT=3000
        ports:
            - "3002:3000"
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: "0.55"
                    memory: "200MB"

    nginx:
        image: nginx:latest
        volumes:
            - ./database/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "30MB"

    db:
     image: mariadb:latest
     hostname: db
     environment:
        - MYSQL_ROOT_PASSWORD=love
        - MYSQL_DATABASE=rinha
        - MYSQL_USER=root
        - MYSQL_PASSWORD=love
     volumes:
        - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
     healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -plove"]
        interval: 10s
        timeout: 5s
        retries: 3
     deploy:
        resources:
            limits:
                cpus: "0.3"
                memory: "120MB"

networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1
