version: "3.8"

services:
  api01: &api
    image: whyakari/rinha:2.0
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    expose:
      - "3030"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  db:
    image: mariadb:latest
    hostname: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=love
      - MYSQL_DATABASE=rinha
      - MYSQL_USER=root
      - MYSQL_PASSWORD=love
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]

    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "230MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

